export type FeishuFieldValue = string | number | boolean | null;

export type FeishuBitableFieldSpec = {
  name: string;
  type: number;
  required?: boolean;
  description: string;
};

export type FeishuBitableViewSpec = {
  name: string;
  view_type: "grid";
  description: string;
  filter_hint: string;
};

export type ModelRegistrySyncEntry = {
  provider: string;
  model: string;
  displayName?: string | null;
  status?: string | null;
  hidden?: boolean | null;
  isAvailable?: boolean | null;
  isFree?: boolean | null;
  rank?: number | null;
  selectionHint?: string | null;
  manualPinned?: boolean | null;
  recentUsed?: boolean | null;
  recentUsedCount?: number | null;
  generatedCommand?: string | null;
  lastProbeAt?: number | null;
  recentUsedAt?: number | null;
  lastSyncAt?: number | null;
  latencyMs?: number | null;
  contextWindow?: number | null;
  reasoning?: boolean | null;
  consecutiveFailures?: number | null;
  failureKind?: string | null;
  lastErrorCode?: string | null;
  lastErrorMessage?: string | null;
  lastFailedAt?: number | null;
  source?: string | null;
  functionType?: string | null;
  taskKinds?: readonly string[] | null;
  modalities?: readonly string[] | null;
  toolCalling?: boolean | null;
  streaming?: boolean | null;
  structuredOutput?: boolean | null;
  vision?: boolean | null;
  maxOutputTokens?: number | null;
  inputPricePerMillion?: number | null;
  outputPricePerMillion?: number | null;
  cacheReadPricePerMillion?: number | null;
  cacheWritePricePerMillion?: number | null;
  rateLimitRpm?: number | null;
  rateLimitTpm?: number | null;
  rateLimitRpd?: number | null;
  burstLimit?: number | null;
  rateLimitWindowSeconds?: number | null;
  cooldownUntil?: number | null;
  healthScore?: number | null;
  successRate?: number | null;
  errorRate?: number | null;
  cacheHitRate?: number | null;
  latencyP50Ms?: number | null;
  latencyP95Ms?: number | null;
  ttfbP50Ms?: number | null;
  ttfbP95Ms?: number | null;
  positiveFeedbackCount?: number | null;
  negativeFeedbackCount?: number | null;
  providerFailureCount?: number | null;
  rateLimitCount?: number | null;
  authErrorCount?: number | null;
  modelNotFoundCount?: number | null;
  gatewayRouteName?: string | null;
  routeFamily?: string | null;
  hiddenReason?: string | null;
  temperatureSupported?: boolean | null;
  topPSupported?: boolean | null;
  jsonModeSupported?: boolean | null;
  parameterSchemaJson?: string | null;
};

export type ModelCatalogRecord = {
  id: string;
  provider: string;
  model: string;
  providerModelKey: string;
  displayName?: string | null;
  status: string;
  hidden: boolean;
  isAvailable: boolean;
  isFree: boolean;
  rank?: number | null;
  selectionHint?: string | null;
  manualPinned: boolean;
  recentUsed: boolean;
  recentUsedCount: number;
  generatedCommand?: string | null;
  lastProbeAt?: number | null;
  recentUsedAt?: number | null;
  lastSyncAt?: number | null;
  latencyMs?: number | null;
  contextWindow?: number | null;
  reasoning?: boolean | null;
  consecutiveFailures: number;
  failureKind?: string | null;
  lastErrorCode?: string | null;
  lastErrorMessage?: string | null;
  lastFailedAt?: number | null;
  source?: string | null;
  functionType?: string | null;
  taskKindsJson: string;
  modalitiesJson: string;
  modelFamily?: string | null;
  modelVersion?: string | null;
  vision?: boolean | null;
  toolCalling?: boolean | null;
  structuredOutput?: boolean | null;
  streaming?: boolean | null;
  maxOutputTokens?: number | null;
  inputPricePerMillion?: number | null;
  outputPricePerMillion?: number | null;
  cacheReadPricePerMillion?: number | null;
  cacheWritePricePerMillion?: number | null;
  temperatureSupported?: boolean | null;
  topPSupported?: boolean | null;
  jsonModeSupported?: boolean | null;
  parameterSchemaJson?: string | null;
  apiFamily?: string | null;
  providerRegion?: string | null;
  createdAt: number;
  updatedAt: number;
};

export type ModelRuntimePolicyRecord = {
  id: string;
  provider: string;
  model: string;
  taskKind: string;
  routeFamily?: string | null;
  gatewayRouteName?: string | null;
  priorityRank: number;
  enabled: boolean;
  hiddenReason?: string | null;
  fallbackAllowed: boolean;
  rateLimitRpm?: number | null;
  rateLimitTpm?: number | null;
  rateLimitRpd?: number | null;
  burstLimit?: number | null;
  rateLimitWindowSeconds?: number | null;
  cooldownUntil?: number | null;
  cacheMode: string;
  cacheTtlSeconds?: number | null;
  cacheScope?: string | null;
  cacheKeyTemplate?: string | null;
  requestTimeoutMs?: number | null;
  maxAttempts?: number | null;
  retryDelayMs?: number | null;
  backoff?: string | null;
  notes?: string | null;
  lastRoutePublishAt?: number | null;
  createdAt: number;
  updatedAt: number;
};

export type ModelHealthStatsRecord = {
  id: string;
  provider: string;
  model: string;
  taskKind: string;
  windowGranularity: string;
  windowStart: number;
  windowEnd: number;
  requestCount: number;
  successCount: number;
  errorCount: number;
  authErrorCount: number;
  modelNotFoundCount: number;
  providerFailureCount: number;
  rateLimitCount: number;
  timeoutCount: number;
  cacheHitCount: number;
  cacheMissCount: number;
  positiveFeedbackCount: number;
  negativeFeedbackCount: number;
  scoreAvg?: number | null;
  healthScore?: number | null;
  successRate?: number | null;
  errorRate?: number | null;
  cacheHitRate?: number | null;
  latencyP50Ms?: number | null;
  latencyP95Ms?: number | null;
  latencyP99Ms?: number | null;
  ttfbP50Ms?: number | null;
  ttfbP95Ms?: number | null;
  ttfbP99Ms?: number | null;
  inputTokensSum: number;
  outputTokensSum: number;
  estimatedCostSum: number;
  createdAt: number;
  updatedAt: number;
};

export type ModelFeedbackEventRecord = {
  id: string;
  provider: string;
  model: string;
  taskKind: string;
  routeFamily?: string | null;
  gatewayRouteName?: string | null;
  gatewayLogId?: string | null;
  correlationId?: string | null;
  feedback?: number | null;
  score?: number | null;
  errorKind?: string | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  latencyMs?: number | null;
  ttfbMs?: number | null;
  cacheStatus?: string | null;
  cacheHit?: boolean | null;
  requestTokens?: number | null;
  responseTokens?: number | null;
  estimatedCost?: number | null;
  metadataJson?: string | null;
  createdAt: number;
};

export type ProviderSyncRunRecord = {
  id: string;
  provider: string;
  source: string;
  runKind: string;
  status: string;
  discoveredModelCount: number;
  upsertedModelCount: number;
  hiddenModelCount: number;
  errorCount: number;
  errorSummary?: string | null;
  startedAt?: number | null;
  completedAt?: number | null;
  createdAt: number;
};
