#!/usr/bin/env python
"""Send a test image and document to Feishu using Hermes' adapter."""

from __future__ import annotations

import argparse
import asyncio
import base64
import os
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from gateway.config import PlatformConfig
from gateway.platforms.feishu import (
    FEISHU_AVAILABLE,
    FEISHU_DOMAIN,
    LARK_DOMAIN,
    FeishuAdapter,
)


_TINY_PNG_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8"
    "/x8AAusB9WlH0xQAAAAASUVORK5CYII="
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Send a test image and document to a Feishu chat using Hermes.",
    )
    parser.add_argument(
        "--chat-id",
        default=os.getenv("FEISHU_HOME_CHANNEL", "").strip(),
        help="Target Feishu chat_id. Defaults to FEISHU_HOME_CHANNEL.",
    )
    parser.add_argument(
        "--document-format",
        choices=("md", "txt"),
        default="md",
        help="Format to use for the generated test document.",
    )
    parser.add_argument(
        "--caption-prefix",
        default="Hermes Feishu attachment test",
        help="Prefix for the image/document caption text.",
    )
    parser.add_argument(
        "--work-dir",
        default="",
        help="Optional directory for generated files. Defaults to a temporary directory.",
    )
    parser.add_argument(
        "--keep-files",
        action="store_true",
        help="Keep generated files after sending.",
    )
    parser.add_argument(
        "--skip-text",
        action="store_true",
        help="Skip the introductory text message and send only attachments.",
    )
    return parser


def _ensure_env() -> None:
    missing = [name for name in ("FEISHU_APP_ID", "FEISHU_APP_SECRET") if not os.getenv(name, "").strip()]
    if missing:
        raise RuntimeError(f"Missing required environment variables: {', '.join(missing)}")
    if not FEISHU_AVAILABLE:
        raise RuntimeError("Feishu dependencies are not installed. Install with `pip install 'hermes-agent[feishu]'`.")


def _create_image(path: Path) -> None:
    path.write_bytes(base64.b64decode(_TINY_PNG_BASE64))


def _create_document(path: Path, *, doc_format: str, chat_id: str) -> None:
    if doc_format == "txt":
        content = (
            "Hermes Feishu document test\n"
            "===========================\n\n"
            f"Target chat: {chat_id}\n"
            "This file was generated by scripts/send_feishu_attachments.py\n"
        )
    else:
        content = (
            "# Hermes Feishu document test\n\n"
            f"- Target chat: `{chat_id}`\n"
            "- Generated by `scripts/send_feishu_attachments.py`\n"
            "- Purpose: verify Feishu native document sending through Hermes\n"
        )
    path.write_text(content, encoding="utf-8")


def _build_adapter() -> FeishuAdapter:
    adapter = FeishuAdapter(PlatformConfig(enabled=True))
    domain = FEISHU_DOMAIN if adapter._domain_name != "lark" else LARK_DOMAIN
    adapter._client = adapter._build_lark_client(domain)
    adapter._running = True
    return adapter


async def _send(args: argparse.Namespace) -> int:
    _ensure_env()
    chat_id = str(args.chat_id or "").strip()
    if not chat_id:
        raise RuntimeError("No target chat_id provided. Pass --chat-id or set FEISHU_HOME_CHANNEL.")

    adapter = _build_adapter()

    temp_dir: str | None = None
    root = Path(args.work_dir).expanduser() if args.work_dir else None
    if root is None:
        temp_dir = tempfile.mkdtemp(prefix="hermes-feishu-attachments-")
        root = Path(temp_dir)
    root.mkdir(parents=True, exist_ok=True)

    image_path = root / "hermes-feishu-test.png"
    document_path = root / f"hermes-feishu-test.{args.document_format}"
    _create_image(image_path)
    _create_document(document_path, doc_format=args.document_format, chat_id=chat_id)

    intro_result = None
    if not args.skip_text:
        intro_result = await adapter.send(
            chat_id=chat_id,
            content=(
                f"{args.caption_prefix}\n"
                f"image={image_path.name}\n"
                f"document={document_path.name}"
            ),
        )

    image_result = await adapter.send_image_file(
        chat_id=chat_id,
        image_path=str(image_path),
        caption=f"{args.caption_prefix} image",
    )
    document_result = await adapter.send_document(
        chat_id=chat_id,
        file_path=str(document_path),
        caption=f"{args.caption_prefix} document",
    )

    print(
        "\n".join(
            [
                f"chat_id={chat_id}",
                f"intro_success={getattr(intro_result, 'success', None)}",
                f"image_success={image_result.success} image_message_id={image_result.message_id} image_error={image_result.error}",
                f"document_success={document_result.success} document_message_id={document_result.message_id} document_error={document_result.error}",
                f"image_path={image_path}",
                f"document_path={document_path}",
            ]
        )
    )

    if temp_dir and not args.keep_files:
        shutil.rmtree(temp_dir, ignore_errors=True)

    return 0 if image_result.success and document_result.success else 1


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()
    try:
        return asyncio.run(_send(args))
    except KeyboardInterrupt:
        return 130
    except Exception as exc:
        print(f"send_feishu_attachments failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
