from __future__ import annotations

import asyncio
import base64
import os
import shutil
import uuid
from pathlib import Path
from typing import Any, Awaitable, Callable


def validate_feishu_native_delivery(
    *,
    target_id: str = "",
    document_format: str = "md",
    caption_prefix: str = "Hermes Feishu native delivery test",
    keep_files: bool = False,
    prepare_runtime_environment: Callable[[], None],
    data_root: Path,
    get_feishu_gateway_runtime: Callable[[], Awaitable[Any]],
    tiny_png_base64: str,
) -> dict[str, Any]:
    prepare_runtime_environment()
    normalized_target_id = str(target_id or os.getenv("FEISHU_HOME_CHANNEL") or "").strip()
    if not normalized_target_id:
        return {
            "status": "error",
            "message": "Provide target_id or set FEISHU_HOME_CHANNEL before validating native Feishu delivery",
        }

    normalized_format = str(document_format or "md").strip().lower() or "md"
    if normalized_format not in {"md", "txt"}:
        return {
            "status": "error",
            "message": "document_format must be one of: md, txt",
        }

    async def _run() -> dict[str, Any]:
        runtime = await get_feishu_gateway_runtime()
        adapter = runtime.adapter

        work_dir = data_root / "feishu-native-delivery" / uuid.uuid4().hex
        work_dir.mkdir(parents=True, exist_ok=True)
        image_path = work_dir / "hermes-feishu-test.png"
        document_path = work_dir / f"hermes-feishu-test.{normalized_format}"

        image_path.write_bytes(base64.b64decode(tiny_png_base64))
        if normalized_format == "txt":
            document_path.write_text(
                (
                    "Hermes Feishu native delivery test\n"
                    "=================================\n\n"
                    f"Target: {normalized_target_id}\n"
                    "This file was generated by validate_feishu_native_delivery.\n"
                ),
                encoding="utf-8",
            )
        else:
            document_path.write_text(
                (
                    "# Hermes Feishu native delivery test\n\n"
                    f"- Target: `{normalized_target_id}`\n"
                    "- Generated by `validate_feishu_native_delivery`\n"
                    "- Purpose: validate native image/document send from the deployed Modal runtime\n"
                ),
                encoding="utf-8",
            )

        image_result = await adapter.send_image_file(
            chat_id=normalized_target_id,
            image_path=str(image_path),
            caption=f"{caption_prefix} image",
        )
        document_result = await adapter.send_document(
            chat_id=normalized_target_id,
            file_path=str(document_path),
            caption=f"{caption_prefix} document",
        )
        payload = {
            "status": "ok" if image_result.success and document_result.success else "error",
            "target_id": normalized_target_id,
            "document_format": normalized_format,
            "image": {
                "success": bool(image_result.success),
                "message_id": image_result.message_id,
                "error": image_result.error,
                "path": str(image_path),
            },
            "document": {
                "success": bool(document_result.success),
                "message_id": document_result.message_id,
                "error": document_result.error,
                "path": str(document_path),
            },
        }
        if not keep_files:
            shutil.rmtree(work_dir, ignore_errors=True)
        return payload

    return asyncio.run(_run())
