from __future__ import annotations

from typing import Any, Callable


def create_web_app(
    *,
    fastapi_cls: Any,
    lifespan_builder: Callable[..., Any],
    startup_tasks_runner: Callable[..., Any],
    feishu_webhook_route_deps_cls: Any,
    register_health_route: Callable[..., None],
    register_invoke_route: Callable[..., None],
    register_internal_feishu_routes: Callable[..., None],
    register_telegram_route: Callable[..., None],
    register_feishu_route: Callable[..., None],
    register_qq_route: Callable[..., None],
    app_name: str,
    default_chat_queue_name: str,
    default_chat_queue_batch_size: int,
    default_feishu_ack_reaction_mode: str,
    supported_feishu_ack_reaction_modes: tuple[str, ...] | list[str],
    default_feishu_ack_reaction_inline_budget_ms: int,
    default_feishu_startup_schema_recheck_seconds: int,
    prepare_runtime_environment: Callable[[], None],
    prewarm_chat_queue_async: Callable[[], Any],
    settings_from_env: Callable[[], Any],
    maybe_sync_telegram_webhook: Callable[[Any], Any],
    load_feishu_sync_state: Callable[[], dict[str, Any]],
    should_prepare_feishu_registry_schema_on_startup: Callable[[dict[str, Any] | None], bool],
    prepare_feishu_model_registry_bitable_impl: Callable[[], dict[str, Any]],
    get_memory_provider_status: Callable[[], dict[str, Any]],
    safe_chat_queue_depth_async: Callable[[], Any],
    cron_status_impl: Callable[[int], dict[str, Any]],
    get_telegram_webhook_status: Callable[[Any], Any],
    build_model_routing_debug_state: Callable[..., dict[str, Any]],
    build_feishu_sync_state_debug_state: Callable[[], dict[str, Any]],
    sync_runtime_config: Callable[[], str],
    serialize_settings_for_log: Callable[[Any], dict[str, Any]],
    validate_bearer_token: Callable[[str | None, str | None], bool],
    validate_feishu_internal_bearer_token: Callable[[str | None, Any], bool],
    run_agent_task_impl: Callable[..., dict[str, Any]],
    handle_internal_json_route: Callable[..., Any],
    authorize_internal_file_route: Callable[..., None],
    log_feishu_internal_auth_failure: Callable[..., None],
    extract_feishu_internal_request_meta: Callable[[dict[str, Any] | None], dict[str, str]],
    run_feishu_internal_agent_exec: Callable[[dict[str, Any]], Any],
    run_feishu_internal_agent_plan: Callable[[dict[str, Any]], Any],
    run_feishu_internal_control: Callable[[dict[str, Any]], Any],
    lookup_feishu_internal_result_file: Callable[[str], dict[str, Any] | None],
    file_response_cls: Any,
    validate_telegram_secret: Callable[[str | None, str | None], bool],
    mark_update_seen: Callable[[str], bool],
    extract_telegram_inline_fast_command: Callable[[dict[str, Any]], str | None],
    dispatch_telegram_update: Callable[[dict[str, Any]], Any],
    send_telegram_message: Callable[[str, str | int, str], Any],
    extract_telegram_queue_context: Callable[[dict[str, Any]], dict[str, str]],
    enqueue_chat_event_async: Callable[..., Any],
    spawn_chat_queue_worker_async: Callable[..., Any],
    feishu_handle_webhook_route: Callable[..., Any],
    try_handle_feishu_verification_fast: Callable[..., Any],
    parse_feishu_webhook_request: Callable[..., Any],
    capture_phase_elapsed: Callable[..., int],
    append_feishu_trace: Callable[..., None],
    extract_feishu_event_metadata: Callable[..., dict[str, Any]],
    mark_feishu_event_seen: Callable[..., bool],
    build_feishu_webhook_ack_response: Callable[..., Any],
    extract_feishu_trace_token: Callable[..., str | None],
    is_feishu_session_warmup_event: Callable[..., bool],
    extract_feishu_warmup_context: Callable[..., dict[str, Any]],
    spawn_feishu_ingress_warmup_async: Callable[..., Any],
    extract_feishu_message_read_event_info: Callable[..., dict[str, Any] | None],
    with_feishu_internal_meta: Callable[..., dict[str, Any]],
    add_feishu_ack_reaction_inline_async: Callable[..., Any],
    spawn_feishu_ack_reaction_async: Callable[..., Any],
    extract_feishu_inline_fast_command: Callable[..., str | None],
    dispatch_feishu_payload: Callable[..., Any],
    send_feishu_local_registry_menu_card: Callable[..., Any],
    extract_feishu_card_action_name: Callable[..., str],
    close_feishu_card_from_payload: Callable[..., Any],
    enqueue_feishu_card_action_for_background: Callable[..., Any],
    build_feishu_card_action_ack_payload: Callable[..., dict[str, Any]],
    should_inline_feishu_control_event: Callable[..., bool],
    extract_feishu_queue_context: Callable[..., dict[str, str]],
    resolve_feishu_message_ingress_strategy: Callable[..., str],
    spawn_feishu_event_handoff_async: Callable[..., Any],
    spawn_feishu_message_inline_async: Callable[..., Any],
    spawn_chat_queue_worker_optimistic_async: Callable[..., Any],
    dispatch_qq_update: Callable[..., Any],
    http_exception_cls: type[Exception],
    json_response_cls: Any,
    logger: Any,
) -> Any:
    async def _run_startup_tasks() -> None:
        await startup_tasks_runner(
            prepare_runtime_environment=prepare_runtime_environment,
            prewarm_chat_queue_async=prewarm_chat_queue_async,
            settings_from_env=settings_from_env,
            maybe_sync_telegram_webhook=maybe_sync_telegram_webhook,
            load_feishu_sync_state=load_feishu_sync_state,
            should_prepare_feishu_registry_schema_on_startup=should_prepare_feishu_registry_schema_on_startup,
            prepare_feishu_model_registry_bitable_impl=prepare_feishu_model_registry_bitable_impl,
            default_feishu_startup_schema_recheck_seconds=default_feishu_startup_schema_recheck_seconds,
            logger=logger,
        )

    def _build_feishu_webhook_route_deps() -> Any:
        return feishu_webhook_route_deps_cls(
            try_handle_verification_fast=try_handle_feishu_verification_fast,
            parse_webhook_request=parse_feishu_webhook_request,
            capture_phase_elapsed=capture_phase_elapsed,
            append_trace=append_feishu_trace,
            extract_event_metadata=extract_feishu_event_metadata,
            mark_event_seen=mark_feishu_event_seen,
            build_ack_response=build_feishu_webhook_ack_response,
            extract_trace_token=extract_feishu_trace_token,
            is_session_warmup_event=is_feishu_session_warmup_event,
            extract_warmup_context=extract_feishu_warmup_context,
            spawn_ingress_warmup_async=spawn_feishu_ingress_warmup_async,
            extract_message_read_event_info=extract_feishu_message_read_event_info,
            with_internal_meta=with_feishu_internal_meta,
            ack_reaction_mode=default_feishu_ack_reaction_mode,
            supported_ack_reaction_modes=supported_feishu_ack_reaction_modes,
            ack_inline_budget_ms=default_feishu_ack_reaction_inline_budget_ms,
            add_ack_reaction_inline_async=add_feishu_ack_reaction_inline_async,
            spawn_ack_reaction_async=spawn_feishu_ack_reaction_async,
            extract_inline_fast_command=extract_feishu_inline_fast_command,
            dispatch_payload=dispatch_feishu_payload,
            send_local_registry_menu_card=send_feishu_local_registry_menu_card,
            extract_card_action_name=extract_feishu_card_action_name,
            close_card_from_payload=close_feishu_card_from_payload,
            enqueue_card_action_for_background=enqueue_feishu_card_action_for_background,
            build_card_action_ack_payload=build_feishu_card_action_ack_payload,
            should_inline_control_event=should_inline_feishu_control_event,
            extract_queue_context=extract_feishu_queue_context,
            resolve_message_ingress_strategy=resolve_feishu_message_ingress_strategy,
            spawn_event_handoff_async=spawn_feishu_event_handoff_async,
            spawn_message_inline_async=spawn_feishu_message_inline_async,
            enqueue_chat_event_async=enqueue_chat_event_async,
            chat_queue_batch_size=default_chat_queue_batch_size,
            spawn_chat_queue_worker_optimistic_async=spawn_chat_queue_worker_optimistic_async,
            http_exception_cls=http_exception_cls,
            json_response_cls=json_response_cls,
            logger=logger,
        )

    app = fastapi_cls(
        title="Hermes Agent Modal Gateway",
        version="1.0.0",
        lifespan=lifespan_builder(startup_tasks=_run_startup_tasks),
    )
    register_health_route(
        app,
        path="/healthz",
        app_name=app_name,
        default_chat_queue_name=default_chat_queue_name,
        prepare_runtime_environment=prepare_runtime_environment,
        settings_from_env=settings_from_env,
        get_memory_provider_status=get_memory_provider_status,
        safe_chat_queue_depth_async=safe_chat_queue_depth_async,
        cron_status_impl=cron_status_impl,
        get_telegram_webhook_status=get_telegram_webhook_status,
        build_model_routing_debug_state=build_model_routing_debug_state,
        build_feishu_sync_state_debug_state=build_feishu_sync_state_debug_state,
        sync_runtime_config=sync_runtime_config,
        serialize_settings_for_log=serialize_settings_for_log,
    )
    register_invoke_route(
        app,
        path="/invoke",
        settings_from_env=settings_from_env,
        validate_bearer_token=validate_bearer_token,
        http_exception_cls=http_exception_cls,
        run_agent_task_impl=run_agent_task_impl,
    )
    register_internal_feishu_routes(
        app,
        settings_from_env=settings_from_env,
        handle_internal_json_route=handle_internal_json_route,
        authorize_internal_file_route=authorize_internal_file_route,
        validate_bearer_token=validate_bearer_token,
        validate_feishu_internal_bearer_token=validate_feishu_internal_bearer_token,
        log_auth_failure=log_feishu_internal_auth_failure,
        extract_request_meta=extract_feishu_internal_request_meta,
        http_exception_cls=http_exception_cls,
        run_internal_agent_exec=run_feishu_internal_agent_exec,
        run_internal_agent_plan=run_feishu_internal_agent_plan,
        run_internal_control=run_feishu_internal_control,
        lookup_internal_result_file=lookup_feishu_internal_result_file,
        file_response_cls=file_response_cls,
        agent_exec_path="/internal/feishu/agent-exec",
        agent_plan_path="/internal/feishu/agent-plan",
        session_control_path="/internal/feishu/session-control",
        result_file_path="/internal/feishu/result-file/{token}",
    )
    register_telegram_route(
        app,
        path="/telegram/webhook",
        settings_from_env=settings_from_env,
        validate_telegram_secret=validate_telegram_secret,
        http_exception_cls=http_exception_cls,
        mark_update_seen=mark_update_seen,
        extract_inline_fast_command=extract_telegram_inline_fast_command,
        dispatch_telegram_update=dispatch_telegram_update,
        send_telegram_message=send_telegram_message,
        extract_telegram_queue_context=extract_telegram_queue_context,
        enqueue_chat_event_async=enqueue_chat_event_async,
        spawn_chat_queue_worker_async=spawn_chat_queue_worker_async,
        default_chat_queue_batch_size=default_chat_queue_batch_size,
        logger=logger,
    )
    register_feishu_route(
        app,
        path="/feishu/webhook",
        settings_from_env=settings_from_env,
        handle_feishu_webhook_route=feishu_handle_webhook_route,
        build_feishu_webhook_deps=_build_feishu_webhook_route_deps,
    )
    register_qq_route(
        app,
        path="/qq/webhook",
        settings_from_env=settings_from_env,
        dispatch_qq_update=dispatch_qq_update,
        http_exception_cls=http_exception_cls,
        logger=logger,
    )
    return app
